return { -- Useful plugin to show you pending keybinds.
	"folke/which-key.nvim",
	event = "VimEnter", -- Sets the loading event to 'VimEnter'
	opts = {
		preset = "helix",
		delay = 0,
		icons = {
			mappings = true,
			-- If you are using a Nerd Font: set icons.keys to an empty table which will use the
			-- default which-key.nvim defined Nerd Font icons, otherwise define a string table
			keys = {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},

		-- Document existing key chains
		spec = {
			{ "<leader>b", group = "Buffer" },
			{ "gr", group = "Lsp" },
			{ "<leader>e", group = "Error" },
			{ "<leader>g", group = "Git", mode = { "n", "v" } },
			{ "<leader>m", group = "Mark" },
			{ "<leader>n", group = "Notifications" },
			{ "<leader>s", group = "Search" },
			{ "<leader>sc", group = "Search Todo-Comment" },
			{ "<leader>t", group = "Tag edit Golang" },
			{ "<leader>ta", group = "Add tag" },
			{ "<leader>tr", group = "Remove tag" },
			{ "[", group = "prev" },
			{ "]", group = "next" },
		},
	},
}
